name: Shadow RDP Lab

on:
  workflow_dispatch:
    inputs:
      ngrok_token:
        description: 'Enter your Ngrok Authtoken'
        required: true

jobs:
  build:
    name: Running Windows VM
    runs-on: windows-latest
    timeout-minutes: 999999

    steps:
    - name: Ngrok টানেল সেটআপ করা... 🌐
      run: |
        choco install ngrok -y
        ngrok config add-authtoken "${{ github.event.inputs.ngrok_token }}"
        
    - name: রিমোট ডেস্কটপ (RDP) সচল ও পাসওয়ার্ড সেট করা 🖥️
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        # এখানে রানারের জন্য পাসওয়ার্ড সেট করা হচ্ছে: Password99@
        $Password = ConvertTo-SecureString "Password99@" -AsPlainText -Force
        Set-LocalUser -Name "runneradmin" -Password $Password
        
    - name: ভার্চুয়াল মেশিন লাইভ রাখা... 🚀
      run: |
        # ব্যাকগ্রাউন্ডে Ngrok চালু করা
        Start-Process ngrok -ArgumentList "tcp --region ap 3389"
        
        # একটু সময় দেওয়া যাতে টানেলটি ড্যাশবোর্ডে চলে আসে
        Start-Sleep 10
        
        $i = 999999
        do {
            Write-Host $i
            Start-Sleep 60
            $i--
        } while ($i -gt 0)
