name: Shadow Ripping Tools Premium

on:
  workflow_dispatch:
    inputs:
      code:
        description: 'Paste Chrome Remote Desktop PowerShell Code Here'
        required: true

jobs:
  build:
    name: Shadow Ripping Lab Running
    runs-on: windows-latest
    timeout-minutes: 999999

    steps:
    - name: ক্রোম রিমোট ডেস্কটপ ডাউনলোড ও ইনস্টল করা... ⚙️
      run: |
        Invoke-WebRequest -Uri "https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi" -OutFile "crd.msi"
        Start-Process msiexec.exe -ArgumentList '/i crd.msi /qn /norestart' -Wait
        
    - name: ক্রোম রিমোট ডেস্কটপ কনফিগার ও চালু করা... 🖥️
      run: |
        # এখানে আপনার গুগলের কোডের শেষে স্পেস দিয়ে --pin=123456 যোগ হয়ে রান হবে
        ${{ github.event.inputs.code }} --pin=123456
        
    - name: ভার্চুয়াল মেশিন সচল রাখা... 🚀
      run: |
        $i = 999999
        do {
            Write-Host "VM is Active - Loop: $i"
            Start-Sleep 60
            $i--
        } while ($i -gt 0)
